stages:
  - build
  - publish

build:linux:
  image: gbraad/godot-server:2.1.4
  stage: build
  script:
    - mkdir -p public/linux
    - godot -export_debug "Linux X11" public/linux/game
  only:
    - master
  artifacts:
    paths:
      - public

build:windows:
  image: gbraad/godot-server:2.1.4
  stage: build
  script:
    - mkdir -p public/windows
    - godot -export_debug "Windows Desktop" public/windows/game.exe
  only:
    - master
  artifacts:
    paths:
      - public

build:html5:
  image: gbraad/godot-server:2.1.4
  stage: build
  script:
    - mkdir -p public/html5
    - godot -export_debug "HTML5" public/html5/game.html
    - mv public/html5/game.html public/html5/index.html
  only:
    - master
  artifacts:
    paths:
      - public

publish:
  image: docker:git
  stage: publish
  script:
    - cd public
    - git init
    - git remote add github https://gbraad:$GITHUB_TOKEN@github.com/gbraad/godot-example-pong.git
    - git add .
    - git config --global user.email "me@gbraad.nl"
    - git config --global user.name "Gerard Braad"
    - "git commit -m 'Deployed by GitLab: https://gitlab.com/gbraad/godot-example-pong'"
    - git branch -m gh-pages
    - git push github :gh-pages || echo 1
    - git push github gh-pages
  when: manual  

pages:
  image: docker:git
  stage: publish
  script:
    - echo
  artifacts:
    paths:
      - public
  only:
    - master

